### PR TITLE
feat(markdown): use npm same markdown parser

### LINKED ISSUE #574: npm markdown and highlight
http://blog.npmjs.org/post/109508231330/nicely-presented-markup

### PR DESCRIPTION
**Pull request by fengmk2**
Fixes #574

### CODE REVIEW

**Comment by fengmk2** [comment]
image

**Comment by fengmk2** [comment]
首页样式有问题

**Comment by fengmk2** [comment]
all fix

**Comment by dead-horse** [comment]
:100:

**Pull request merged**
