### PR TITLE
fix: don't sync constructor package on exists mode

### LINKED ISSUE #857: Syncs package named "constructor" on new installation
As mentioned [here](https://github.com/cnpm/cnpmjs.org/issues/793#issuecomment-176733092).

Clean installation of CNPM (no published packages): http://snag.gy/z02Z5.jpg

If you click the link to `constructor`, it takes you to a page that says `Can not found package match constructor. You can SYNC from official npm registry or SEARCH in official npm website.`.

What is this package?

### PR DESCRIPTION
**Pull request by fengmk2**
closes #857

### CODE REVIEW

**Comment by fengmk2** [comment]
cc @glen-84

**Comment by fengmk2** [comment]
2.9.4

**Comment by glen-84** [comment]
Thank you so much! I will test this early next week.

**Comment by glen-84** [comment]
Verified fixed. :+1:

**Pull request merged**
