### PR TITLE
Obfuscate email address, fixes #1373

### LINKED ISSUE #1373: Leaking package author email address to pubic
Hi there.

The website https://cnpmjs.org is leaking package author's email addresses to pubic. Bots can scrape the site and can spam easily.

Take this example https://cnpmjs.org/~yyx990803
If you view source `view-source:https://cnpmjs.org/~yyx990803` of the page; you will find that email address is visible and has not been obfuscated.

Email addresses are also visible to Google (see screenshot)
screenshot from 2018-08-19 09 23 16

You should have been using packages like:
https://www.npmjs.com/package/obfooscator
Obfuscate strings ensure that spam bots can not harvest them.

The official npmjs site does not show email address at all. See
https://www.npmjs.com/~yyx990803

Thanks.

### PR DESCRIPTION
**Pull request by ankurk91**
Fixes #1373

Using this package
~~https://github.com/donburks/obfooscator~~
https://www.npmjs.com/package/he

### CODE REVIEW

**Comment by fengmk2** [comment]
CI fails on `obfooscator/unicode_lookup.js`

```
{ TypeError: Cannot read property 'uni' of undefined
    at module.exports (/home/travis/build/cnpm/cnpmjs.org/node_modules/obfooscator/unicode_lookup.js:43:23)
    at obfooscator (/home/travis/build/cnpm/cnpmjs.org/node_modules/obfooscator/obfooscator.js:17:24)
    at Object.showUser (/home/travis/build/cnpm/cnpmjs.org/controllers/web/user/show.js:9:1600)
```

**Comment by ankurk91** [comment]
Thanks for reporting excact error, it was hard for me find out it from logs.

I will fix it soon. I think email is `null` in some cases.

**Comment by ankurk91** [comment]
I tried my best to figure out why it is failing.
Does email address has characters that the obfooscator cant handle?
For what email address it is failing?

**Comment by fengmk2** [comment]
@ankurk91 Look good to me if you can add a test case for this change?

**Comment by fengmk2** [comment]
@ankurk91 Look good to me if you can add a test case for this change?

**Comment by fengmk2** [comment]
@ankurk91 Look good to me if you can add a test case for this change?

**Comment by ankurk91** [comment]
GitHub is having issues today. Will do ASAP.

**Comment by ankurk91** [comment]
@fengmk2 
I have added test case. Please check.

**Pull request merged**
